version: '3'

services:

  web:
    container_name: mowgli-web
    image: nginx
    ports:
      - 4005:80
    volumes:
      - ./web:/usr/share/nginx/html:ro
    restart: unless-stopped

  mosquitto:
    container_name: mowgli-mqtt
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  roscore:
    container_name: mowgli-roscore
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo
    network_mode: host
    #pull_policy: always
    tty: true
    privileged: true
    command:
      - /opt/ros/noetic/bin/roscore
    environment:
      ROS_IP: ${ROS_IP}
      ROSCONSOLE_CONFIG_FILE: /config/rosconsole.config
      ROSOUT_DISABLE_FILE_LOGGING: true
    tmpfs: /root/.ros/log/
    volumes:
      - ./config/om:/config:ro
      - ./ros:/root/.ros/
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  rosserial:
    container_name: mowgli-rosserial
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo
    network_mode: host
    #pull_policy: always
    tty: true
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      ROS_MASTER_URI: http://${ROS_IP}:11311
      ROS_IP: ${ROS_IP}
      ROSCONSOLE_CONFIG_FILE: /config/rosconsole.config
      ROSOUT_DISABLE_FILE_LOGGING: true
    command:
      - /opt/ros/noetic/bin/rosrun
      - rosserial_server
      - serial_node
      - _port:=/dev/mowgli
      - _baud:=115200
    tmpfs: /root/.ros/log/
    volumes:
      - ./ros:/root/.ros/
      - ./config/om:/config:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    depends_on:
      - roscore
    restart: unless-stopped

  openmower:
    container_name: mowgli-openmower
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo
    network_mode: host
    #pull_policy: always
    tty: true
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      ROS_MASTER_URI: http://${ROS_IP}:11311
      ROS_IP: ${ROS_IP}
      ROSCONSOLE_CONFIG_FILE: /config/rosconsole.config   # comment this line out to enable more logs
      ROSOUT_DISABLE_FILE_LOGGING: true                   # comment this line out to enable more logs
    tmpfs: /root/.ros/log                          # comment this line out to enable persistent logs
    volumes:
      - ./config/om:/config:ro
      - ./mower_params:/root/mower_params:ro
      - ./params:/opt/open_mower_ros/src/open_mower/params:ro
      - ./ros:/root/.ros/
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    depends_on:
      - rosserial
    restart: unless-stopped
